version: '3'
services:
  # backend
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
    container_name: node