version: '3'
services:
  # frontend
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4444"
    container_name: node
