version: '3.7'

services:
  ts-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev

#     // PROD compose
#
#version: '3.7'
#
#services:
#  ts-node-docker:
#    build:
#      target: production
#    command: node build/index.js
#
#